# Generated by Django 4.2.3 on 2023-07-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.DecimalField(decimal_places=2, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
